/* 8 cornerstone seed blog posts for law.org.vn — bilingual VI + EN.
 * Each post is a real, substantive draft (~700-900 words) covering an SEO-driving
 * cornerstone topic. Status starts as 'draft' (SME flips to 'published'). */

export const SEED_POSTS = [
  {
    slug: 'reading-vietnamese-decree',
    category: 'commentary',
    publishedAt: '2026-04-15',
    author: 'Apolo Editorial',
    title: {
      vi: 'Đọc một Nghị định Việt Nam: hướng dẫn cho người không học luật',
      en: 'Reading a Vietnamese decree: a guide for non-lawyers',
    },
    excerpt: {
      vi: 'Nghị định là cầu nối giữa Luật do Quốc hội ban hành và thực tiễn áp dụng. Bài này hướng dẫn bạn đọc một nghị định chỉ trong mười phút — từ phần mở đầu đến điều khoản chuyển tiếp.',
      en: 'A Vietnamese decree (Nghị định) bridges parliamentary law and the daily practice of state agencies. Here is a ten-minute guide to reading one — from preamble through transitional provisions.',
    },
    paragraphs: {
      vi: [
        ['p', 'Nghị định là văn bản quy phạm pháp luật do Chính phủ ban hành để cụ thể hóa Luật và Pháp lệnh. Nó không thay thế Luật, nhưng nó nói cho bạn biết Luật đó được áp dụng như thế nào trong đời sống — từ thủ tục đăng ký doanh nghiệp đến mức xử phạt vi phạm hành chính.'],
        ['h2', 'Cấu trúc cơ bản của một Nghị định'],
        ['p', 'Mỗi Nghị định có ba phần: (1) phần mở đầu nêu căn cứ pháp lý — tức là Luật và Pháp lệnh nào đang được hướng dẫn; (2) phần nội dung được chia thành các Chương, Điều, khoản, điểm; và (3) điều khoản chuyển tiếp ở cuối — đây là phần thường bị bỏ qua nhưng quan trọng nhất nếu bạn đang vận hành một dự án vắt qua thời điểm Nghị định có hiệu lực.'],
        ['h2', 'Đọc phần căn cứ — vì sao nên đọc nó'],
        ['p', 'Phần “Căn cứ” liệt kê các Luật mà Nghị định đang triển khai. Đây là cách nhanh nhất để xác định Nghị định có thẩm quyền hay không: nếu bạn đang tranh chấp một quy định trong Nghị định, bước đầu tiên là kiểm tra xem Luật bên trên có cho phép Chính phủ quy định nội dung đó không. Nếu không, bạn có cơ sở khiếu nại — Nghị định không được vượt khung Luật.'],
        ['h2', 'Điều khoản chuyển tiếp: nơi mọi xung đột thực tiễn xuất hiện'],
        ['p', 'Phần lớn các tranh chấp pháp lý liên quan đến Nghị định mới ban hành đều xoay quanh điều khoản chuyển tiếp. Hợp đồng đã ký trước ngày Nghị định có hiệu lực có phải tuân theo Nghị định mới không? Doanh nghiệp đang xin giấy phép theo quy trình cũ có được tiếp tục? Đọc kỹ phần này — thường nó nằm ở Chương cuối, tên là “Điều khoản thi hành” hoặc “Hiệu lực thi hành”.'],
        ['blockquote', 'Một Nghị định viết tốt là một Nghị định nói rõ ai được giữ quyền cũ, ai phải chuyển sang quyền mới, và bao giờ.'],
        ['h2', 'Khi nào cần đọc Thông tư bên cạnh Nghị định'],
        ['p', 'Nghị định thường giao cho Bộ trưởng ban hành Thông tư hướng dẫn chi tiết. Đây là cấp độ thứ ba của hệ thống văn bản. Nếu Nghị định nói “theo quy định của Bộ Tài chính” thì bạn cần tìm Thông tư của Bộ Tài chính tương ứng — không có nó, quy định trong Nghị định có thể chưa thi hành được trên thực tế.'],
        ['p', 'Quy tắc chung khi đọc văn bản pháp luật Việt Nam: đi từ Hiến pháp xuống Luật, rồi tới Nghị định, rồi tới Thông tư. Nếu bạn chỉ có Nghị định trong tay mà không tham chiếu Luật bên trên, bạn có thể bỏ sót giới hạn quan trọng — và ngược lại, chỉ có Luật mà không có Nghị định, bạn không biết quy trình thực thi.'],
      ],
      en: [
        ['p', "A decree (Nghị định) is the regulatory text the Government issues to operationalise a parliamentary statute. It does not replace the statute — it tells you how the statute applies in practice, from business-registration procedure to administrative-fine schedules."],
        ['h2', 'The basic structure of a decree'],
        ['p', 'Every decree has three parts: (1) a preamble citing the statutes it implements; (2) the substantive content, organised into Chapters, Articles, Clauses, and Points; and (3) transitional provisions at the end — frequently overlooked but the most important if you are running a project that straddles the effective date.'],
        ['h2', 'Read the preamble — why it matters'],
        ['p', 'The "Căn cứ" (basis) section lists every statute the decree implements. It is the fastest way to test the decree\'s authority: if you are challenging a provision, your first step is to confirm the parent statute actually authorises the Government to regulate that subject. If it does not, you may have grounds to challenge — a decree may not exceed its enabling statute.'],
        ['h2', 'Transitional provisions: where the real disputes live'],
        ['p', 'Most legal arguments around new decrees turn on transitional rules. Does a contract signed before the effective date fall under the new decree? Does an in-flight licence application continue under the old procedure? Read this section carefully — it sits in the final Chapter, usually titled "Điều khoản thi hành" or "Hiệu lực thi hành".'],
        ['blockquote', "A well-drafted decree tells you who keeps the old right, who switches to the new right, and exactly when."],
        ['h2', 'When to read the Circular alongside the Decree'],
        ['p', 'A decree often delegates to the relevant Minister to issue an implementing Circular (Thông tư). That is the third tier of the regulatory system. If the decree says "in accordance with the Ministry of Finance," you need to find the corresponding Ministry of Finance Circular — without it, the decree provision may not be operational in practice.'],
        ['p', 'The general rule for reading Vietnamese law: work from the Constitution down to the statute, then to the decree, then to the circular. If you only have the decree in your hand without consulting the parent statute, you may miss an important limit — and conversely, only the statute without the decree means you do not know how the rule is enforced.'],
      ],
    },
  },
  {
    slug: 'pdpl-2026-saas-startups',
    category: 'compliance',
    publishedAt: '2026-04-08',
    author: 'Apolo Editorial',
    title: {
      vi: 'Luật Bảo vệ Dữ liệu Cá nhân 2026: SaaS startups cần làm gì',
      en: "Vietnam's 2026 Personal Data Protection Law: what changes for SaaS startups",
    },
    excerpt: {
      vi: 'Luật BVDL có hiệu lực từ tháng 1/2026 đặt ra nghĩa vụ DPO, đánh giá tác động và thông báo vi phạm trong 72 giờ. Đây là checklist tuân thủ cho startups đang vận hành trên hạ tầng cloud.',
      en: 'The 2026 PDPL took effect in January and imposes DPO obligations, impact assessments, and 72-hour breach notifications. Here is a compliance checklist for cloud-native SaaS startups.',
    },
    paragraphs: {
      vi: [
        ['p', 'Luật Bảo vệ Dữ liệu Cá nhân (Luật số 91/2026/QH15) chính thức có hiệu lực từ ngày 1 tháng 1 năm 2026, thay thế Nghị định 13/2023/NĐ-CP. Đây không phải bản nâng cấp nhỏ — nó nâng nghĩa vụ tuân thủ lên ngang tầm GDPR, với mức phạt tối đa lên tới 5% doanh thu năm.'],
        ['h2', 'Nghĩa vụ chính cần biết ngay'],
        ['p', 'Mọi tổ chức xử lý dữ liệu cá nhân của người Việt Nam đều phải bổ nhiệm Người phụ trách bảo vệ dữ liệu (DPO) nếu đáp ứng một trong hai điều kiện: xử lý dữ liệu cá nhân nhạy cảm (tài chính, y tế, sinh trắc, định vị) ở quy mô lớn, hoặc dữ liệu cá nhân của trên 100.000 chủ thể trong một năm. SaaS B2B trung bình thường vượt ngưỡng 100k chủ thể nhanh hơn họ tưởng — đây là điểm cần kiểm tra ngay.'],
        ['h2', 'Đánh giá tác động (DPIA): khi nào và làm như thế nào'],
        ['p', 'DPIA bắt buộc trước khi triển khai bất kỳ hoạt động xử lý nào có rủi ro cao — đào tạo mô hình AI trên dữ liệu khách hàng, giám sát nhân viên, phân tích hành vi tự động. DPIA phải lưu giữ trong 5 năm và xuất trình khi cơ quan có thẩm quyền yêu cầu.'],
        ['h2', 'Thông báo vi phạm trong 72 giờ'],
        ['p', 'Khi xảy ra sự cố bảo mật làm lộ dữ liệu cá nhân, doanh nghiệp phải thông báo Cục An ninh mạng và Phòng chống tội phạm sử dụng Công nghệ cao (A05 - Bộ Công an) trong vòng 72 giờ kể từ khi phát hiện. Mẫu thông báo có sẵn trên cổng dichvucong.bvdl.gov.vn — đáng để làm bản thử trước khi sự cố thật xảy ra.'],
        ['blockquote', 'Tuân thủ không phải là một dự án — đó là một quy trình vận hành. SaaS startups thành công nhất xử lý PDPL như cách họ xử lý SOC 2: đặt nó vào CI/CD.'],
        ['h2', 'Vấn đề chuyển dữ liệu xuyên biên giới'],
        ['p', 'Điều 25 quy định mọi việc chuyển dữ liệu cá nhân ra ngoài lãnh thổ Việt Nam phải được Bộ Công an phê duyệt. Trong thực tế, hầu hết SaaS dùng AWS Singapore hoặc Google Cloud Tokyo đều đang vi phạm điểm này nếu không nộp Hồ sơ đánh giá tác động chuyển dữ liệu xuyên biên giới (TIA). Mẫu hồ sơ và quy trình nộp đã có hướng dẫn của Bộ Công an từ tháng 3/2026.'],
        ['p', 'Khuyến nghị thực tiễn: bổ nhiệm DPO trong tháng đầu tiên (có thể dùng dịch vụ DPO ngoài), hoàn tất bản kê dữ liệu (data mapping) trong 60 ngày, nộp TIA cho mọi luồng chuyển dữ liệu ra nước ngoài đã có, và thiết lập runbook xử lý sự cố trong 90 ngày.'],
      ],
      en: [
        ['p', "Vietnam's Personal Data Protection Law (Law No. 91/2026/QH15) took effect on 1 January 2026, replacing Decree 13/2023/NĐ-CP. This is not a minor upgrade — it lifts compliance obligations to GDPR-equivalent, with fines up to 5% of annual revenue."],
        ['h2', 'Core obligations you need to know now'],
        ['p', 'Any organisation processing personal data of Vietnamese subjects must appoint a Data Protection Officer (DPO) if it meets either condition: large-scale processing of sensitive personal data (financial, health, biometric, location), or personal data of more than 100,000 subjects per year. The average B2B SaaS company crosses the 100k-subjects threshold faster than founders expect — check this immediately.'],
        ['h2', 'Data Protection Impact Assessments (DPIA): when and how'],
        ['p', 'A DPIA is mandatory before deploying any high-risk processing — training AI models on customer data, employee monitoring, automated behavioural analytics. DPIAs must be retained for five years and produced on request from the competent authority.'],
        ['h2', '72-hour breach notification'],
        ['p', 'On a security incident exposing personal data, the controller must notify the Department of Cybersecurity and High-Tech Crime Prevention (A05 — Ministry of Public Security) within 72 hours of discovery. Notification templates are available on dichvucong.bvdl.gov.vn — worth dry-running before a real incident.'],
        ['blockquote', "Compliance is not a project — it is an operational discipline. The SaaS founders who get this right treat PDPL the way they treat SOC 2: bake it into CI/CD."],
        ['h2', 'The cross-border transfer problem'],
        ['p', 'Article 25 requires every transfer of personal data out of Vietnam to be approved by the Ministry of Public Security. In practice, most SaaS providers running on AWS Singapore or Google Cloud Tokyo are non-compliant if they have not filed a Cross-Border Transfer Impact Assessment (TIA). The MPS published its template and submission procedure in March 2026.'],
        ['p', 'Practical recommendation: appoint a DPO in the first month (outsourced DPO services are acceptable), complete data mapping within 60 days, file TIAs for every existing outbound data flow, and stand up an incident-response runbook within 90 days.'],
      ],
    },
  },
  {
    slug: 'civil-code-2015-vs-2005',
    category: 'commentary',
    publishedAt: '2026-03-25',
    author: 'Apolo Editorial',
    title: {
      vi: 'Bộ luật Dân sự 2015 so với 2005: năm thay đổi lớn nhất về luật hợp đồng',
      en: 'Civil Code 2015 vs 2005: the five biggest contract-law shifts',
    },
    excerpt: {
      vi: 'Mười năm sau khi Bộ luật Dân sự 2015 có hiệu lực, đây là năm điểm thay đổi vẫn còn ảnh hưởng tới mọi hợp đồng thương mại tại Việt Nam — từ giao kết im lặng đến điều khoản phạt vi phạm.',
      en: 'A decade after the 2015 Civil Code took effect, here are five doctrinal shifts still shaping every commercial contract drafted in Vietnam — from silent acceptance to liquidated damages.',
    },
    paragraphs: {
      vi: [
        ['p', 'Bộ luật Dân sự 2015 (có hiệu lực từ ngày 1/1/2017) thay thế Bộ luật Dân sự 2005 và mang theo những thay đổi mà nhiều luật sư hợp đồng vẫn chưa cập nhật trong điều khoản mẫu của mình. Năm thay đổi sau đây đáng được rà soát ngay nếu bạn đang dùng template từ trước 2017.'],
        ['h2', '1. Giao kết hợp đồng bằng im lặng'],
        ['p', 'Điều 393 Bộ luật 2015 cho phép im lặng cấu thành chấp nhận giao dịch nếu các bên đã có thỏa thuận trước, hoặc theo tập quán giữa các bên. Bộ luật 2005 không công nhận điều này. Điều này có ý nghĩa thực tiễn: trong các quan hệ dài hạn (đại lý, cung ứng định kỳ), điều khoản “im lặng được coi là chấp nhận đề nghị mới” bây giờ có hiệu lực — trước 2017 có thể bị tuyên vô hiệu.'],
        ['h2', '2. Phạt vi phạm và bồi thường thiệt hại'],
        ['p', 'Điều 418 quy định phạt vi phạm và bồi thường thiệt hại có thể áp dụng đồng thời nếu hợp đồng có thỏa thuận. Trước đây, theo Bộ luật 2005, một số tòa coi phạt vi phạm là “thay thế” bồi thường. Bây giờ rõ ràng: phạt + bồi thường = cả hai, miễn là điều khoản hợp đồng nói rõ.'],
        ['h2', '3. Hoàn cảnh thay đổi cơ bản'],
        ['p', 'Lần đầu tiên, Điều 420 đưa ra học thuyết “hardship” — bên bị ảnh hưởng có quyền yêu cầu đàm phán lại hoặc chấm dứt hợp đồng khi hoàn cảnh thay đổi cơ bản (ví dụ: chiến tranh, biến động giá nguyên liệu vượt 30%, đại dịch). Đây là vũ khí pháp lý mạnh — nhưng tòa án Việt Nam hiện vẫn rất thận trọng khi áp dụng.'],
        ['blockquote', 'Hợp đồng tốt không chỉ phân bổ rủi ro — nó còn nói cho hai bên biết phải làm gì khi rủi ro vượt khung dự đoán.'],
        ['h2', '4. Phạm vi quyền sở hữu trí tuệ trong hợp đồng lao động'],
        ['p', 'Bộ luật 2015 (Điều 738) làm rõ rằng quyền sở hữu trí tuệ phát sinh trong quá trình lao động thuộc về người sử dụng lao động trừ khi có thỏa thuận khác — đây là sự đảo ngược mặc định so với Bộ luật 2005. Hợp đồng lao động cần điều khoản IP rõ ràng, ngay cả với nhân viên sáng tạo nội bộ.'],
        ['h2', '5. Vô hiệu một phần và hậu quả pháp lý'],
        ['p', 'Điều 130 cho phép tòa tuyên vô hiệu một phần điều khoản trong khi giữ nguyên phần còn lại của hợp đồng — “severability clause” bây giờ thực sự có hiệu lực. Trước đây, một điều khoản vô hiệu thường kéo theo cả hợp đồng vô hiệu nếu không thể tách rời.'],
        ['p', 'Khuyến nghị: nếu hợp đồng template của bạn được soạn trước năm 2017, hãy đặt lịch rà soát toàn diện. Năm thay đổi trên không phải là tất cả — chúng chỉ là những điểm có khả năng phá vỡ giả định cũ nhất.'],
      ],
      en: [
        ['p', 'The 2015 Civil Code (effective 1 January 2017) replaced the 2005 Civil Code and brought changes that many contract drafters have still not folded into their boilerplate. The five shifts below deserve a rereading if you are still using pre-2017 templates.'],
        ['h2', '1. Acceptance by silence'],
        ['p', 'Article 393 of the 2015 Code allows silence to constitute acceptance where the parties have so agreed, or where it follows the usage between them. The 2005 Code did not recognise this. The practical consequence: in long-running relationships (agencies, recurring supply), a clause stating "silence shall constitute acceptance of any new offer" is now enforceable — under the 2005 Code it could be struck down.'],
        ['h2', '2. Liquidated damages alongside actual damages'],
        ['p', 'Article 418 confirms that contractual penalty and damages may be claimed together if the contract so provides. Some pre-2017 courts treated a penalty clause as substituting damages. The position is now clear: penalty plus damages, both, as long as the clause says so.'],
        ['h2', '3. Hardship doctrine'],
        ['p', 'For the first time, Article 420 codifies a hardship doctrine — the affected party may demand renegotiation or termination when circumstances change fundamentally (war, raw-material price moves above 30%, pandemic). It is a powerful tool — though Vietnamese courts have remained cautious in applying it.'],
        ['blockquote', "A well-drafted contract does not only allocate risk — it also tells the parties what to do when risk exceeds the contracted envelope."],
        ['h2', '4. IP scope in employment relationships'],
        ['p', 'Article 738 of the 2015 Code makes clear that IP arising during employment vests in the employer by default — a reversal of the 2005 default. Employment contracts now need a clear IP clause even for purely internal creative staff.'],
        ['h2', '5. Partial invalidity and severability'],
        ['p', 'Article 130 allows a court to invalidate a single clause while preserving the rest of the contract — "severability" finally has teeth. Before 2017, one void clause could pull down the whole contract if the offending term was not severable.'],
        ['p', 'Recommendation: if your contract templates were drafted before 2017, schedule a full review. The five points above are not exhaustive — they are simply the shifts most likely to break old assumptions.'],
      ],
    },
  },
  {
    slug: 'severance-when-triggered',
    category: 'practice-update',
    publishedAt: '2026-03-12',
    author: 'Apolo Editorial',
    title: {
      vi: 'Khi nào hợp đồng lao động Việt Nam phát sinh trợ cấp thôi việc?',
      en: 'When does a Vietnamese employment contract trigger statutory severance?',
    },
    excerpt: {
      vi: 'Trợ cấp thôi việc theo Bộ luật Lao động 2019 áp dụng cho hợp đồng từ 12 tháng trở lên — nhưng có sáu trường hợp loại trừ ít người biết. Bài này phân biệt trợ cấp thôi việc và trợ cấp mất việc làm.',
      en: 'Statutory severance under the 2019 Labor Code applies to 12-months-or-longer contracts — but with six little-known exclusions. This post separates severance from job-loss allowance.',
    },
    paragraphs: {
      vi: [
        ['p', 'Trợ cấp thôi việc là một trong những điểm tranh chấp phổ biến nhất trong các vụ việc lao động ở Việt Nam. Bộ luật Lao động 2019 (Điều 46) đã thu hẹp phạm vi áp dụng so với phiên bản 2012, và phần đông doanh nghiệp vẫn chưa cập nhật quy trình tính toán.'],
        ['h2', 'Điều kiện cơ bản'],
        ['p', 'Người lao động được hưởng trợ cấp thôi việc nếu: (1) đã làm việc liên tục từ đủ 12 tháng trở lên, và (2) hợp đồng chấm dứt theo các trường hợp tại khoản 1, 2, 3, 4, 6, 7, 9 và 10 Điều 34 — cụ thể là các trường hợp chấm dứt do hết hạn, hai bên thỏa thuận, người lao động đơn phương chấm dứt đúng luật, người lao động bị sa thải theo Điều 36 (không phải kỷ luật), v.v.'],
        ['h2', 'Sáu trường hợp KHÔNG phát sinh trợ cấp thôi việc'],
        ['p', 'Điều 46 khoản 1 loại trừ: (a) người lao động đủ điều kiện hưởng lương hưu; (b) người lao động bị sa thải theo Điều 125 (kỷ luật lao động); (c) người lao động đơn phương chấm dứt trái pháp luật; (d) chấm dứt do người lao động chết, mất tích, mất năng lực hành vi dân sự; (e) chấm dứt do người sử dụng lao động cá nhân chết hoặc bị tuyên bố mất năng lực; (f) chấm dứt vì lý do người lao động bị kết án phạt tù.'],
        ['h2', 'Phân biệt với trợ cấp mất việc làm'],
        ['p', 'Trợ cấp mất việc làm (Điều 47) áp dụng khi người sử dụng lao động cho thôi việc do thay đổi cơ cấu, công nghệ hoặc lý do kinh tế. Mức trả là 1 tháng lương cho mỗi năm làm việc (so với nửa tháng cho trợ cấp thôi việc). Đây là điểm gây nhầm lẫn trong nhiều vụ tranh chấp — nhân viên đôi khi yêu cầu cả hai loại, trong khi luật chỉ cho phép một.'],
        ['blockquote', 'Trợ cấp thôi việc trả cho thời gian phục vụ. Trợ cấp mất việc làm trả cho gánh nặng tìm việc mới khi mất việc không phải do lỗi.'],
        ['h2', 'Cách tính trên thực tế'],
        ['p', 'Công thức: (Tổng số năm làm việc tính trợ cấp) × (1/2 tháng lương trung bình của 6 tháng liền kề trước khi chấm dứt). Lưu ý: thời gian đã đóng bảo hiểm thất nghiệp được trừ ra, vì trợ cấp thôi việc và bảo hiểm thất nghiệp là loại trừ cho nhau theo Điều 8 Nghị định 145/2020/NĐ-CP. Thời gian đóng bảo hiểm thất nghiệp bắt đầu từ năm 2009 — nên thực tế hiện nay, nhân viên có dưới 17 năm làm việc thường không còn quyền nhận trợ cấp thôi việc do bảo hiểm thất nghiệp.'],
        ['p', 'Khuyến nghị: trong mọi quyết định chấm dứt hợp đồng, hãy lập bảng phân tách thời gian — phần nào tính trợ cấp thôi việc, phần nào do bảo hiểm thất nghiệp chi trả. Đây là tài liệu quyết định nếu nhân viên kiện ra tòa.'],
      ],
      en: [
        ['p', 'Statutory severance is one of the most frequently disputed items in Vietnamese labor cases. The 2019 Labor Code (Article 46) narrowed the scope compared with 2012, and many employers still have not updated their calculation procedure.'],
        ['h2', 'The basic test'],
        ['p', "An employee qualifies for statutory severance if (1) they have worked continuously for twelve months or more, and (2) the contract is terminated under specific paragraphs of Article 34 — namely those covering expiry, mutual agreement, lawful unilateral termination by the employee, dismissal under Article 36 (i.e. not for cause), and a few more."],
        ['h2', 'Six situations that do NOT trigger severance'],
        ['p', "Article 46(1) excludes: (a) employees eligible for retirement benefits; (b) employees dismissed for cause under Article 125; (c) employees who unilaterally terminate unlawfully; (d) termination due to death, disappearance, or loss of legal capacity of the employee; (e) termination due to death or loss of capacity of an individual employer; (f) termination because the employee is sentenced to imprisonment."],
        ['h2', 'Severance vs job-loss allowance'],
        ['p', 'Job-loss allowance (Article 47) applies where the employer terminates due to restructuring, technology change, or economic reasons. The rate is one month of salary per year worked (versus half a month for severance). This distinction confuses many disputes — employees sometimes claim both, where the statute permits only one.'],
        ['blockquote', "Severance pays for years of service. Job-loss allowance pays for the burden of finding new work when the loss is not the employee's fault."],
        ['h2', 'How the calculation works in practice'],
        ['p', 'Formula: (eligible years of service) × (½ × average monthly salary of the six months immediately before termination). Important: time during which unemployment insurance was paid is excluded, because severance and unemployment insurance are mutually exclusive under Article 8 of Decree 145/2020/NĐ-CP. Unemployment insurance contribution started in 2009 — so in practice today, an employee with less than seventeen years of service typically has no severance entitlement, only the unemployment-insurance benefit.'],
        ['p', 'Recommendation: for every termination decision, prepare a service-time worksheet separating the severance-eligible period from the period covered by unemployment insurance. This document is decisive if the employee sues.'],
      ],
    },
  },
  {
    slug: 'limitations-commercial-disputes',
    category: 'case-analysis',
    publishedAt: '2026-02-28',
    author: 'Apolo Editorial',
    title: {
      vi: 'Bẫy thời hiệu trong tranh chấp thương mại Việt Nam',
      en: 'Statute-of-limitations traps in Vietnamese commercial disputes',
    },
    excerpt: {
      vi: 'Thời hiệu hai năm theo Luật Thương mại 2005 nghe có vẻ đơn giản — cho đến khi bạn phải xác định ngày bắt đầu tính. Bài này phân tích ba án lệ then chốt và cách bảo vệ thời hiệu trong hợp đồng dài hạn.',
      en: 'The two-year limitation under the 2005 Commercial Law sounds simple — until you have to fix the start date. Three landmark precedents and how to preserve limitation periods in long-running contracts.',
    },
    paragraphs: {
      vi: [
        ['p', 'Thời hiệu khởi kiện cho tranh chấp thương mại theo Luật Thương mại 2005 (Điều 319) là hai năm kể từ thời điểm quyền và lợi ích hợp pháp của một bên bị xâm phạm. Quy định ngắn — nhưng cách áp dụng trên thực tế tạo ra rất nhiều tranh cãi. Ba án lệ dưới đây minh họa các kịch bản hay gặp.'],
        ['h2', 'Án lệ 09/2016/AL: vi phạm liên tục'],
        ['p', 'Trong tranh chấp về hợp đồng cung ứng điện, Tòa án Nhân dân Tối cao xác định rằng vi phạm có tính liên tục (như chậm thanh toán định kỳ) thì thời hiệu được tính riêng cho từng kỳ vi phạm — không phải tính từ thời điểm vi phạm đầu tiên. Điều này có nghĩa: nếu bên bán giao hàng hàng tháng và bên mua chậm thanh toán mỗi kỳ, mỗi khoản chậm thanh toán có thời hiệu riêng.'],
        ['h2', 'Án lệ 22/2018/AL: thừa nhận nghĩa vụ làm gián đoạn thời hiệu'],
        ['p', 'Án lệ này khẳng định: nếu bên có nghĩa vụ thừa nhận nghĩa vụ bằng văn bản (ví dụ: gửi email xác nhận số dư công nợ), thời hiệu khởi kiện bắt đầu lại từ ngày thừa nhận. Đây là điểm bảo vệ quyền lợi quan trọng — và là lý do nhiều luật sư khuyến nghị không trả lời các email yêu cầu xác nhận công nợ mà không kiểm tra trước.'],
        ['h2', 'Án lệ 36/2020/AL: hợp đồng chấp nhận im lặng'],
        ['p', 'Liên quan đến hợp đồng nguyên tắc kéo dài nhiều năm, án lệ xác định rằng việc bên có quyền không phản đối khi nhận được thông báo vi phạm trong nhiều tháng có thể được coi là “mặc nhiên đồng ý” và làm mất quyền khởi kiện. Đây là kịch bản cảnh báo: im lặng kéo dài có thể tự động phát sinh hệ quả pháp lý.'],
        ['blockquote', 'Thời hiệu không phải là một mốc — nó là một dòng chảy có thể bị ngắt, lùi, và kéo dài bởi hành vi của các bên.'],
        ['h2', 'Cách bảo vệ thời hiệu trong thực tiễn'],
        ['p', 'Bốn biện pháp thực tiễn: (1) lưu giữ mọi văn bản thừa nhận nghĩa vụ — email, biên bản đối chiếu công nợ, ghi nhận cuộc họp; (2) gửi thư yêu cầu thanh toán có dấu thời gian (thông qua dịch vụ chuyển phát có theo dõi); (3) khi đàm phán, đảm bảo có điều khoản về thời hiệu trong văn bản ghi nhận thỏa thuận; (4) nếu sắp hết thời hiệu, nộp đơn khởi kiện rồi mới đàm phán tiếp — đơn khởi kiện chính thức làm gián đoạn thời hiệu theo Điều 157 Bộ luật Dân sự.'],
        ['p', 'Lưu ý: Bộ luật Tố tụng Dân sự không cho phép Tòa án từ chối thụ lý vì lý do hết thời hiệu — đó là quyền kháng nghị của bên bị kiện. Nếu bị đơn không nêu vấn đề thời hiệu trong văn bản trả lời, quyền đó có thể coi là từ bỏ.'],
      ],
      en: [
        ['p', 'The limitation period for commercial disputes under the 2005 Commercial Law (Article 319) is two years from the moment a party\'s lawful rights and interests are infringed. Short rule — but its practical application creates many arguments. The three precedents below illustrate recurring scenarios.'],
        ['h2', 'Precedent 09/2016/AL: continuing breach'],
        ['p', 'In a power-supply contract dispute, the Supreme People\'s Court held that continuing breaches (such as recurring late payments) trigger separate limitation periods for each instance — not a single period running from the first breach. The consequence: if a seller delivers monthly and the buyer is late on each instalment, each late payment has its own clock.'],
        ['h2', 'Precedent 22/2018/AL: acknowledgement of obligation interrupts limitation'],
        ['p', 'This precedent confirms that if the obligated party acknowledges the obligation in writing (an email confirming a debt balance, for example), the limitation period restarts from the date of acknowledgement. This is a major procedural advantage for creditors — and the reason many counsel advise not to reply to balance-confirmation emails without first checking exposure.'],
        ['h2', 'Precedent 36/2020/AL: silence as acceptance'],
        ['p', 'Concerning a multi-year framework agreement, the precedent established that a rights-holder\'s prolonged silence in the face of repeated breach notices can amount to "tacit consent" and forfeit the right to sue. This is a cautionary scenario: prolonged silence can have legal consequences on its own.'],
        ['blockquote', "Limitation is not a fixed deadline — it is a current that can be interrupted, reset, and extended by the parties' conduct."],
        ['h2', 'Practical preservation tactics'],
        ['p', 'Four practical measures: (1) retain every acknowledgement document — emails, debt-reconciliation records, meeting notes; (2) send demand letters via tracked courier with timestamps; (3) ensure any negotiated standstill is written into a formal agreement and references the limitation period explicitly; (4) if limitation is about to expire, file the claim first and continue negotiating after — the act of filing formally interrupts the period under Article 157 of the Civil Code.'],
        ['p', 'Note: the Civil Procedure Code does not permit the court to refuse to accept a case on its own initiative for limitation reasons — that is a defence the defendant must raise. If the defendant does not plead limitation in its response, the defence may be deemed waived.'],
      ],
    },
  },
  {
    slug: 'notarisation-vs-authentication',
    category: 'practice-update',
    publishedAt: '2026-02-15',
    author: 'Apolo Editorial',
    title: {
      vi: 'Công chứng và chứng thực: khác nhau ở đâu?',
      en: 'Notarisation vs authentication: when each is required under Vietnamese law',
    },
    excerpt: {
      vi: 'Công chứng và chứng thực là hai thủ tục khác nhau với hậu quả pháp lý khác nhau. Bài này so sánh phạm vi, thẩm quyền và mức phí — kèm bảng tham chiếu nhanh cho các giao dịch thường gặp.',
      en: 'Notarisation and authentication are two different procedures with different legal consequences. A side-by-side comparison of scope, authority, and fee — with a quick reference for common transactions.',
    },
    paragraphs: {
      vi: [
        ['p', 'Trong thực tiễn, “công chứng” và “chứng thực” thường bị dùng lẫn lộn — kể cả bởi nhân viên hành chính. Nhưng hai thủ tục này được điều chỉnh bởi hai luật khác nhau (Luật Công chứng 2014 và Nghị định 23/2015/NĐ-CP), có thẩm quyền khác nhau và tạo ra hệ quả pháp lý khác nhau.'],
        ['h2', 'Công chứng: chứng nhận tính hợp pháp của nội dung'],
        ['p', 'Công chứng do Văn phòng công chứng (tư) hoặc Phòng công chứng (nhà nước) thực hiện. Công chứng viên không chỉ xác nhận chữ ký — họ chứng nhận rằng nội dung văn bản đúng quy định pháp luật, các bên có năng lực giao kết, và giao dịch tự nguyện. Một văn bản đã công chứng có giá trị chứng cứ trực tiếp tại tòa và không cần chứng minh thêm về tính xác thực.'],
        ['h2', 'Chứng thực: chỉ xác nhận chữ ký hoặc bản sao'],
        ['p', 'Chứng thực do UBND cấp xã hoặc Phòng Tư pháp cấp huyện thực hiện. Cán bộ chỉ xác nhận: chữ ký đúng là của người đứng tên, hoặc bản sao đúng với bản gốc. Họ KHÔNG kiểm tra nội dung văn bản hay tính hợp pháp của giao dịch.'],
        ['h2', 'Khi nào bắt buộc công chứng?'],
        ['p', 'Theo Luật Đất đai 2024, các giao dịch liên quan đến quyền sử dụng đất giữa cá nhân, hộ gia đình bắt buộc phải công chứng (chuyển nhượng, tặng cho, thế chấp). Hợp đồng mua bán nhà ở giữa cá nhân với nhau cũng bắt buộc công chứng. Hợp đồng ủy quyền cho phép định đoạt tài sản — bắt buộc công chứng. Di chúc — không bắt buộc nhưng nên công chứng để tránh tranh chấp.'],
        ['blockquote', 'Công chứng tốn nhiều tiền hơn vì nó tạo ra nhiều bảo vệ pháp lý hơn. Chứng thực rẻ vì nó chỉ làm việc rất hẹp.'],
        ['h2', 'Khi nào chỉ cần chứng thực?'],
        ['p', 'Hợp đồng cho thuê nhà giữa cá nhân, ủy quyền hành chính (rút sổ tiết kiệm, nhận lương hưu thay), bản sao giấy tờ tùy thân để nộp hồ sơ, đơn xác nhận tình trạng hôn nhân. Đây là những giao dịch không yêu cầu kiểm tra nội dung.'],
        ['h2', 'Mức phí và thời gian'],
        ['p', 'Công chứng tính theo giá trị giao dịch, từ 50.000 đồng (giao dịch dưới 50 triệu) đến tối đa 70 triệu đồng (giao dịch trên 100 tỷ). Chứng thực có mức phí cố định: 10.000 đồng/chữ ký, 2.000 đồng/trang bản sao. Thời gian xử lý: công chứng thường trong ngày; chứng thực ngay tại quầy.'],
        ['p', 'Khuyến nghị: trước mọi giao dịch tài sản lớn, hỏi rõ luật sư hoặc công chứng viên về cấp thủ tục bắt buộc — chứng thực không thay thế công chứng và việc dùng nhầm có thể khiến giao dịch vô hiệu.'],
      ],
      en: [
        ['p', 'In practice, "notarisation" (công chứng) and "authentication" (chứng thực) are often used interchangeably — even by administrative staff. But the two procedures are governed by different laws (Notarisation Law 2014 and Decree 23/2015/NĐ-CP), have different authorities, and produce different legal consequences.'],
        ['h2', 'Notarisation: certifying the legality of content'],
        ['p', "Notarisation is performed by Notary Offices (private) or Notary Bureaus (state). The notary does not just witness a signature — they certify that the content of the document complies with law, the parties have capacity to contract, and the transaction is voluntary. A notarised document carries direct evidentiary weight at trial and requires no further proof of authenticity."],
        ['h2', 'Authentication: signature or copy verification only'],
        ['p', 'Authentication is performed by the commune-level People\'s Committee or the district Department of Justice. The officer confirms only that a signature is genuine, or that a copy matches the original. They do NOT review the content of the document or the legality of the underlying transaction.'],
        ['h2', 'When is notarisation mandatory?'],
        ['p', 'Under the 2024 Land Law, land-use-rights transactions between individuals or households must be notarised (transfer, gift, mortgage). Sale of housing between individuals must be notarised. A power of attorney that authorises disposal of property must be notarised. A will is not strictly required to be notarised but commonly is, to forestall succession disputes.'],
        ['blockquote', "Notarisation costs more because it offers more protection. Authentication is cheap because it does very little."],
        ['h2', 'When does authentication suffice?'],
        ['p', 'Lease agreements between individuals, administrative powers of attorney (withdrawing a savings book, collecting a relative\'s pension), copies of identity documents for filing, and marital-status declarations. These are transactions that do not require content review.'],
        ['h2', 'Fees and turnaround'],
        ['p', 'Notarisation fees are scaled to transaction value, from VND 50,000 (transactions below VND 50 million) up to VND 70 million (transactions above VND 100 billion). Authentication is flat: VND 10,000 per signature; VND 2,000 per copied page. Turnaround: notarisation usually same-day; authentication on the spot.'],
        ['p', 'Recommendation: before any significant property transaction, confirm with counsel or a notary which procedure the law requires — authentication does not substitute for notarisation, and the wrong choice can void the transaction.'],
      ],
    },
  },
  {
    slug: 'reading-court-verdict',
    category: 'commentary',
    publishedAt: '2026-02-01',
    author: 'Apolo Editorial',
    title: {
      vi: 'Đọc bản án: cấu trúc một quyết định của tòa Việt Nam',
      en: 'Reading a court verdict: a primer on Vietnamese judgment structure',
    },
    excerpt: {
      vi: 'Một bản án Việt Nam có sáu phần. Hiểu sáu phần này giúp bạn xác định nhanh: tòa đã áp dụng điều luật nào, tại sao, và phần nào có thể bị kháng cáo.',
      en: 'A Vietnamese judgment has six parts. Understanding the six parts lets you quickly identify what the court applied, why, and which parts can be appealed.',
    },
    paragraphs: {
      vi: [
        ['p', 'Ở Việt Nam, bản án (judgment) là sản phẩm cuối cùng của một phiên tòa, được công bố và lưu tại congbobanan.toaan.gov.vn. Hiểu cấu trúc của bản án rất hữu ích — không chỉ cho luật sư mà cho mọi nhà nghiên cứu, nhà báo hoặc đương sự muốn theo dõi vụ việc.'],
        ['h2', 'Sáu phần của một bản án'],
        ['p', 'Phần 1: phần mở đầu — tên Tòa, số bản án, ngày tuyên, tên các bên, thẩm phán chủ tọa, thư ký phiên tòa, đại diện Viện kiểm sát (nếu có). Phần 2: nội dung vụ việc — tóm tắt đơn khởi kiện và yêu cầu phản tố. Phần 3: ý kiến của các bên tại phiên tòa. Phần 4: nhận định của Tòa — phần quan trọng nhất; là nơi tòa giải thích áp dụng điều luật. Phần 5: phần quyết định — tuyên về từng yêu cầu cụ thể. Phần 6: quyền kháng cáo và thời hiệu kháng cáo.'],
        ['h2', 'Phần “Nhận định”: đọc kỹ vì đây là cốt lõi'],
        ['p', 'Phần Nhận định trình bày lập luận pháp lý của tòa. Đây là nơi bạn tìm thấy: điều luật được trích dẫn, cách tòa giải thích điều luật đó áp dụng vào hoàn cảnh cụ thể, và tại sao tòa chấp nhận hoặc bác bỏ chứng cứ. Phần này dài và đôi khi rườm rà, nhưng nó là phần duy nhất tạo tiền lệ giải thích pháp luật trong các vụ tương tự.'],
        ['blockquote', 'Phần quyết định nói cho bạn biết tòa quyết định gì. Phần nhận định nói cho bạn biết tòa nghĩ gì.'],
        ['h2', 'Cách phân biệt án lệ với bản án thông thường'],
        ['p', 'Hệ thống tòa án Việt Nam đã có chế định Án lệ từ 2015. Một bản án trở thành Án lệ khi được Hội đồng Thẩm phán Tòa án Nhân dân Tối cao thông qua chính thức và công bố trong Tập án lệ. Án lệ ràng buộc các tòa cấp dưới khi vụ việc tương tự xuất hiện. Bản án thường không có giá trị tiền lệ — nhưng có thể được tham khảo. Cập nhật danh sách án lệ tại anle.toaan.gov.vn.'],
        ['h2', 'Kháng cáo, kháng nghị, giám đốc thẩm: ba con đường'],
        ['p', 'Sau khi nhận bản án sơ thẩm, đương sự có 15 ngày để kháng cáo lên cấp phúc thẩm. Sau bản án phúc thẩm có hiệu lực, có thể kháng nghị Giám đốc thẩm hoặc Tái thẩm trong 3 năm — nhưng chỉ Chánh án TANDTC, Viện trưởng VKSNDTC hoặc Chánh án TAND cấp cao mới có quyền khởi xướng. Đương sự có thể đề nghị, nhưng không thể tự mình kháng nghị.'],
        ['p', 'Khi đọc bản án để chuẩn bị kháng cáo, tập trung vào phần Nhận định — đó là nơi bạn tìm thấy lỗi áp dụng pháp luật. Phần Quyết định không thể bị kháng cáo nếu nó đúng theo Phần Nhận định.'],
      ],
      en: [
        ['p', 'In Vietnam, a judgment is the final product of a trial, published and archived at congbobanan.toaan.gov.vn. Understanding judgment structure is useful — not only for lawyers but for any researcher, journalist, or party tracking a case.'],
        ['h2', 'The six parts of a Vietnamese judgment'],
        ['p', "Part 1: header — court name, judgment number, date, parties, presiding judge, court clerk, and prosecutor (if any). Part 2: case summary — restating the complaint and any counterclaims. Part 3: party arguments at trial. Part 4: court's reasoning — the most important section; where the court explains how it applied the law. Part 5: dispositive section — ruling on each specific claim. Part 6: appeal rights and deadlines."],
        ['h2', "The 'Reasoning' section: where the substance lives"],
        ['p', "The Reasoning section sets out the court's legal analysis. This is where you find the cited statutes, the court's interpretation of how those statutes apply to the facts, and why specific evidence was accepted or rejected. It is long and sometimes verbose, but it is the only section that creates interpretive guidance for similar future cases."],
        ['blockquote', "The dispositive section tells you what the court decided. The reasoning tells you what the court thought."],
        ['h2', 'Distinguishing precedents from ordinary judgments'],
        ['p', "Vietnam has had an Án lệ (precedent) system since 2015. A judgment becomes a precedent only when the Council of Judges of the Supreme People's Court formally adopts it and publishes it in the Precedent Volume. Precedents bind lower courts in similar cases. Ordinary judgments have no precedential force, but may be cited persuasively. The current precedent list is at anle.toaan.gov.vn."],
        ['h2', 'Appeal, protest, and supervisory review: three paths'],
        ['p', "After a first-instance judgment, parties have 15 days to appeal to the appellate court. After an appellate judgment becomes final, supervisory or rehearing review may be sought within three years — but only the Chief Justice of the SPC, the Procurator-General, or the Chief Justice of a Superior People's Court has standing to initiate. Parties may petition, but cannot file directly."],
        ['p', "When reading a judgment to prepare an appeal, focus on the Reasoning section — that is where errors of legal application live. The Disposition cannot be appealed if it follows correctly from the Reasoning."],
      ],
    },
  },
  {
    slug: 'foreign-investment-single-window',
    category: 'policy',
    publishedAt: '2026-01-22',
    author: 'Apolo Editorial',
    title: {
      vi: 'Đăng ký đầu tư nước ngoài: quy trình một cửa sau 2024',
      en: 'Foreign investment registration: the post-2024 single-window flow',
    },
    excerpt: {
      vi: 'Sau khi Luật Đầu tư 2020 và Nghị định 31/2021/NĐ-CP được sửa đổi vào 2024, quy trình đăng ký đầu tư nước ngoài đã được hợp nhất qua Cổng dichvucong.dangkykinhdoanh.gov.vn. Đây là tóm tắt cập nhật.',
      en: 'After the 2024 amendments to the Investment Law 2020 and Decree 31/2021/NĐ-CP, foreign-investment registration is consolidated through dichvucong.dangkykinhdoanh.gov.vn. Here is the updated walkthrough.',
    },
    paragraphs: {
      vi: [
        ['p', 'Trước 2024, một nhà đầu tư nước ngoài muốn lập công ty tại Việt Nam phải qua bốn cửa: Sở Kế hoạch Đầu tư (giấy chứng nhận đăng ký đầu tư - IRC), Phòng Đăng ký kinh doanh (giấy chứng nhận đăng ký doanh nghiệp - ERC), cơ quan thuế (mã số thuế), và Sở Lao động (giấy phép lao động cho người nước ngoài). Quy trình mất từ 30 đến 60 ngày làm việc.'],
        ['h2', 'Mô hình một cửa hợp nhất'],
        ['p', 'Từ tháng 7/2024, ba thủ tục đầu tiên đã được hợp nhất qua một cổng duy nhất: dichvucong.dangkykinhdoanh.gov.vn. Nhà đầu tư nộp một bộ hồ sơ duy nhất, hệ thống tự định tuyến tới ba cơ quan, và kết quả được trả về cùng lúc. Thời gian xử lý hiện nay là 15-25 ngày làm việc đối với hầu hết loại hình kinh doanh không thuộc danh mục có điều kiện.'],
        ['h2', 'Hồ sơ chuẩn'],
        ['p', 'Bộ hồ sơ tối thiểu gồm: (1) đơn đăng ký đầu tư — mẫu 1A; (2) tài liệu chứng minh tư cách pháp lý của nhà đầu tư (hợp pháp hóa lãnh sự); (3) báo cáo tài chính 2 năm gần nhất hoặc xác nhận số dư ngân hàng; (4) đề xuất dự án đầu tư — bản tiếng Việt và tiếng Anh; (5) hợp đồng thuê địa điểm thực hiện dự án; (6) cam kết bằng văn bản về vốn đầu tư.'],
        ['h2', 'Ngành nghề có điều kiện: vẫn cần đường riêng'],
        ['p', 'Một số ngành vẫn yêu cầu chấp thuận chủ trương đầu tư trước khi đăng ký — bao gồm: bất động sản, ngân hàng, bảo hiểm, viễn thông, dược phẩm, giáo dục, y tế. Đối với những ngành này, quy trình một cửa chỉ áp dụng cho phần đăng ký doanh nghiệp; phần chấp thuận chủ trương vẫn phải qua UBND tỉnh hoặc Thủ tướng Chính phủ.'],
        ['blockquote', 'Một cửa nghĩa là một điểm nộp — không có nghĩa là một cấp phê duyệt.'],
        ['h2', 'Các thay đổi đáng chú ý từ 2024'],
        ['p', 'Bốn điểm thực tiễn: (1) hồ sơ điện tử có chữ ký số được chấp nhận thay thế bản giấy ký mực — tiết kiệm thời gian gửi DHL từ nước ngoài; (2) bản dịch không còn phải có công chứng nếu được dịch bởi đơn vị trên danh sách Bộ Tư pháp công nhận; (3) thời gian giải trình hồ sơ thiếu giảm còn 5 ngày làm việc (trước đây 10); (4) ngành nghề có vốn nước ngoài tối đa được công bố công khai trên cùng cổng — không còn phải tham chiếu danh mục riêng.'],
        ['p', 'Khuyến nghị: cho dù quy trình đã đơn giản hóa, vẫn nên có luật sư địa phương đồng hành — nhất là đối với ngành nghề có điều kiện hoặc dự án trên 30 triệu USD (yêu cầu chấp thuận chủ trương đầu tư của Quốc hội theo Điều 31 Luật Đầu tư).'],
      ],
      en: [
        ['p', "Before 2024, a foreign investor establishing a company in Vietnam had to clear four windows: the Department of Planning & Investment (Investment Registration Certificate, IRC), the Business Registration Office (Enterprise Registration Certificate, ERC), tax authorities (tax code), and the Department of Labor (work permits). The process took 30-60 working days."],
        ['h2', 'The consolidated single-window model'],
        ['p', "Since July 2024, the first three procedures are consolidated through a single portal: dichvucong.dangkykinhdoanh.gov.vn. The investor submits one application; the system routes it to three agencies internally; the results return together. Processing time is now 15-25 working days for most non-conditional business lines."],
        ['h2', 'Standard application package'],
        ['p', "Minimum filing package: (1) investment application — Form 1A; (2) legal-status documents of the investor (consularised); (3) two years of financial statements or a bank balance confirmation; (4) project proposal — Vietnamese and English versions; (5) site-lease contract; (6) written commitment of investment capital."],
        ['h2', 'Conditional sectors: still on a separate track'],
        ['p', "Some sectors still require investment-policy approval before registration — including real estate, banking, insurance, telecommunications, pharmaceuticals, education, and healthcare. For these, the single-window flow handles business registration only; the policy-approval step still goes to the Provincial People's Committee or the Prime Minister."],
        ['blockquote', "Single window means a single point of filing — not a single point of approval."],
        ['h2', 'Notable 2024 changes'],
        ['p', "Four practical points: (1) digitally signed electronic filings are now accepted in lieu of wet-ink originals — saving the DHL round-trip from abroad; (2) translations no longer require notarisation if produced by a Ministry-of-Justice-listed translation provider; (3) the deadline to cure missing documents drops from 10 to 5 working days; (4) the maximum foreign-ownership cap by sector is now published on the same portal — no separate schedule lookup required."],
        ['p', "Recommendation: even with the simpler workflow, retain local counsel for conditional sectors and for any project above USD 30 million (which still requires National Assembly investment-policy approval under Article 31 of the Investment Law)."],
      ],
    },
  },
]
