#!/usr/bin/env node
/* Rewrite src/lib/images.ts from a published manifest after PM runs tools/image-generator-ui /batch.
 * The batch tool uploads to R2 and emits a JSON with each image's `r2_url`, `width`, `height`, `alt_vi`, `alt_en`.
 *
 * Expected input: content/images-published.json (copy from the batch tool's output).
 */
import fs from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const manifestPath = path.resolve(__dirname, '..', 'content', 'images-published.json')
const outputPath = path.resolve(__dirname, '..', 'src', 'lib', 'images.ts')

const manifest = JSON.parse(await fs.readFile(manifestPath, 'utf8'))
const R2_BASE = 'https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/law.org.vn'

function camelCase(id) {
  return id.replace(/[-_]([a-z])/g, (_, c) => c.toUpperCase())
}

const entries = manifest.images
  .filter((img) => img.status === 'published' && img.r2_url)
  .map((img) => {
    const key = camelCase(img.id)
    const alt = (img.alt_en || img.alt_vi || img.name || img.id).replace(/'/g, "\\'")
    return `  ${key}: { src: '${img.r2_url}', width: ${img.width}, height: ${img.height}, alt: '${alt}' },`
  })
  .join('\n')

const out = `// Generated by scripts/implement-assets.mjs from content/images-published.json.
// Regenerate after adding or updating images via tools/image-generator-ui /batch.

const R2_BASE = '${R2_BASE}'

type ImageEntry = {
  src: string
  width: number
  height: number
  alt: string
}

export const images = {
${entries}
} satisfies Record<string, ImageEntry>

export type ImageKey = keyof typeof images

export { R2_BASE }
`

await fs.writeFile(outputPath, out, 'utf8')
console.log(`[implement-assets] wrote ${manifest.images.length} entries → ${path.relative(process.cwd(), outputPath)}`)
